apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: hygieia-api
  name: hygieia-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hygieia-api
    spec:
      containers:
      - env:
        - name: SPRING_DATA_MONGODB_DATABASE
          value: dashboarddb
        - name: SPRING_DATA_MONGODB_HOST
          value: mongodb
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: password
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_USERNAME
          value: dashboarduser
        image: capitalone/hygieia-api:latest
        name: hygieia-api
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /hygieia/logs
          name: hygieia-api-claim0
      restartPolicy: Always
      volumes:
      - name: hygieia-api-claim0
        persistentVolumeClaim:
          claimName: hygieia-api-claim0
status: {}
